services:
  - type: static
    name: cafe-management-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - path: /*
        destination: /index.html
